import { createHmac } from "node:crypto";
import { NextResponse } from "next/server";
import { durableRateLimit, requestIp, serviceHeaders, supabaseUrl, userHeaders } from "@/lib/launch-server";

type User = { id?: string };
function fingerprint(value:string){const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!key)throw new Error("Session security is not configured.");return createHmac("sha256",key).update(value).digest("hex");}
function browserFamily(value:string){const a=value.toLowerCase();const browser=a.includes("edg/")?"Edge":a.includes("firefox/")?"Firefox":a.includes("chrome/")?"Chrome":a.includes("safari/")?"Safari":"Other browser";const platform=a.includes("windows")?"Windows":a.includes("android")?"Android":a.includes("iphone")||a.includes("ipad")?"iOS":a.includes("mac os")?"macOS":a.includes("linux")?"Linux":"Unknown device";return `${browser} on ${platform}`;}
async function identity(request:Request){const authorization=request.headers.get("authorization")??"",token=authorization.match(/^Bearer\s+(\S+)$/i)?.[1];if(!token)throw new Response("Authentication required.",{status:401});const response=await fetch(`${supabaseUrl()}/auth/v1/user`,{headers:userHeaders(authorization),cache:"no-store"});if(!response.ok)throw new Response("Invalid or expired session.",{status:401});const user=await response.json() as User;if(!user.id)throw new Response("Invalid account session.",{status:401});return{authorization,token,userId:user.id};}
function denied(reason:unknown){if(reason instanceof Response)return NextResponse.json({error:reason.status===401?"Authentication required.":"Access denied."},{status:reason.status});return NextResponse.json({error:reason instanceof Error?reason.message:"Security request failed."},{status:500});}

export async function GET(request:Request){try{const{token,userId}=await identity(request),currentHash=fingerprint(token),headers=serviceHeaders();const[sessionsResponse,eventsResponse]=await Promise.all([fetch(`${supabaseUrl()}/rest/v1/user_sessions?user_id=eq.${encodeURIComponent(userId)}&select=id,session_hash,user_agent_family,last_seen_at,revoked_at,created_at&order=last_seen_at.desc&limit=25`,{headers,cache:"no-store"}),fetch(`${supabaseUrl()}/rest/v1/security_events?user_id=eq.${encodeURIComponent(userId)}&select=id,event_type,severity,safe_details,created_at&order=created_at.desc&limit=25`,{headers,cache:"no-store"})]);if(!sessionsResponse.ok||!eventsResponse.ok)return NextResponse.json({error:"The account security migration is required."},{status:503});const sessions=await sessionsResponse.json() as Array<Record<string,unknown>>;return NextResponse.json({sessions:sessions.map(({session_hash,...session})=>({...session,current:session_hash===currentHash})),events:await eventsResponse.json()});}catch(reason){return denied(reason);}}

export async function POST(request:Request){const limit=await durableRateLimit(`session-touch:${requestIp(request)}`,20,60_000);if(!limit.allowed)return NextResponse.json({error:"Too many session updates."},{status:429});try{const{token,userId}=await identity(request);const values={user_id:userId,session_hash:fingerprint(token),ip_hash:fingerprint(requestIp(request)),user_agent_family:browserFamily(request.headers.get("user-agent")??""),last_seen_at:new Date().toISOString(),revoked_at:null};const response=await fetch(`${supabaseUrl()}/rest/v1/user_sessions?on_conflict=session_hash`,{method:"POST",headers:{...serviceHeaders(),Prefer:"resolution=merge-duplicates,return=minimal"},body:JSON.stringify(values)});if(!response.ok)return NextResponse.json({error:"The account security migration is required."},{status:503});return NextResponse.json({tracked:true});}catch(reason){return denied(reason);}}

export async function DELETE(request:Request){const limit=await durableRateLimit(`session-revoke:${requestIp(request)}`,5,10*60_000);if(!limit.allowed)return NextResponse.json({error:"Too many sign-out requests."},{status:429});try{const{authorization,userId}=await identity(request);const logout=await fetch(`${supabaseUrl()}/auth/v1/logout?scope=global`,{method:"POST",headers:userHeaders(authorization)});if(!logout.ok)return NextResponse.json({error:"Supabase could not revoke the sessions."},{status:503});const now=new Date().toISOString(),headers=serviceHeaders();await Promise.all([fetch(`${supabaseUrl()}/rest/v1/user_sessions?user_id=eq.${encodeURIComponent(userId)}&revoked_at=is.null`,{method:"PATCH",headers:{...headers,Prefer:"return=minimal"},body:JSON.stringify({revoked_at:now})}),fetch(`${supabaseUrl()}/rest/v1/security_events`,{method:"POST",headers:{...headers,Prefer:"return=minimal"},body:JSON.stringify({user_id:userId,event_type:"all_sessions_revoked",severity:"warning",user_agent_family:browserFamily(request.headers.get("user-agent")??""),safe_details:{initiated_by_customer:true}})})]);return NextResponse.json({revoked:true});}catch(reason){return denied(reason);}}
