"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { RefreshCw, Search, ShieldCheck } from "lucide-react";
import { parseApiResponse } from "@/lib/client-api";
import { createClient } from "@/lib/supabase-browser";

type RecordItem={id:number;actor_id:string|null;action:string;entity_type:string;entity_id:string|null;details:Record<string,unknown>;created_at:string};

export default function Page(){
  const [records,setRecords]=useState<RecordItem[]>([]),[action,setAction]=useState(""),[entity,setEntity]=useState(""),[notice,setNotice]=useState("Loading audit records...");
  async function load(){setNotice("Loading audit records...");try{const{data}=await createClient().auth.getSession();if(!data.session?.access_token)throw new Error("Admin sign-in required.");const params=new URLSearchParams({limit:"300"});if(action.trim())params.set("action",action.trim());if(entity.trim())params.set("entity",entity.trim());const payload=await parseApiResponse(await fetch(`/api/admin/audit?${params}`,{headers:{Authorization:`Bearer ${data.session.access_token}`},cache:"no-store"}));setRecords(Array.isArray(payload.records)?payload.records as RecordItem[]:[]);setNotice("");}catch(reason){setRecords([]);setNotice(reason instanceof Error?reason.message:"Audit records could not be loaded.");}}
  // Initial authorization and audit fetch; filters are submitted explicitly.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(()=>{void load();},[]);
  function submit(event:FormEvent){event.preventDefault();void load();}
  return <main className="mx-auto min-h-[800px] max-w-7xl px-6 py-14"><section className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-sm font-black uppercase tracking-[.2em] text-amber-400">Admin security</p><h1 className="mt-3 text-4xl font-black">Audit trail.</h1><p className="mt-3 max-w-2xl text-white/40">Review sensitive staff actions by actor, action, entity, timestamp, and recorded details.</p></div><Link href="/admin" className="font-bold text-amber-300">Back to operations</Link></section><form onSubmit={submit} className="mt-8 grid gap-3 md:grid-cols-[1fr_1fr_auto]"><label className="flex min-h-12 items-center gap-3 rounded-xl border border-white/10 px-4"><Search size={17}/><input value={action} onChange={event=>setAction(event.target.value)} placeholder="Action contains..." className="w-full bg-transparent outline-none"/></label><label className="flex min-h-12 items-center gap-3 rounded-xl border border-white/10 px-4"><ShieldCheck size={17}/><input value={entity} onChange={event=>setEntity(event.target.value)} placeholder="Entity type contains..." className="w-full bg-transparent outline-none"/></label><button className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-amber-400 px-5 font-black text-black"><RefreshCw size={17}/>Load</button></form>{notice&&<p role="status" className="mt-5 rounded-xl border border-white/10 p-4 text-sm text-white/55">{notice}</p>}<div className="mt-6 overflow-x-auto rounded-3xl border border-white/10 bg-white/[.02]"><table className="w-full min-w-[1040px] text-left text-sm"><thead className="bg-white/[.04] text-xs font-black uppercase tracking-[.12em] text-white/35"><tr><th className="p-5">Time</th><th>Action</th><th>Entity</th><th>Actor</th><th className="pr-5">Details</th></tr></thead><tbody>{records.map(record=><tr key={record.id} className="border-t border-white/8 align-top"><td className="p-5 whitespace-nowrap">{new Date(record.created_at).toLocaleString()}</td><td className="font-black text-amber-200">{record.action}</td><td>{record.entity_type}{record.entity_id&&<span className="mt-1 block max-w-52 truncate font-mono text-xs text-white/35" title={record.entity_id}>{record.entity_id}</span>}</td><td className="max-w-48 truncate font-mono text-xs text-white/50" title={record.actor_id??"System"}>{record.actor_id??"System"}</td><td className="max-w-md py-5 pr-5"><pre className="whitespace-pre-wrap break-words rounded-xl bg-black/20 p-3 text-xs text-white/55">{JSON.stringify(record.details??{},null,2)}</pre></td></tr>)}</tbody></table>{!records.length&&!notice&&<p className="p-10 text-center text-white/35">No audit records match these filters.</p>}</div></main>;
}
