-- Capture legacy production audit and automatic-RLS objects in the canonical chain.
-- Remove baseline-only order mutation logic superseded by server-authoritative APIs.
drop trigger if exists secure_order_values on public.orders;
drop function if exists public.secure_order_values();

drop policy if exists "profiles update own" on public.profiles;
create policy "profiles update own"
on public.profiles for update to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);
drop function if exists public.current_user_role();

create table if not exists public.order_status_audit (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  reference text not null,
  previous_status text,
  new_status text not null,
  changed_by uuid references auth.users(id) on delete set null,
  changed_at timestamptz not null default now()
);

alter table public.order_status_audit enable row level security;
create index if not exists order_status_audit_order_id_idx on public.order_status_audit(order_id);
create index if not exists order_status_audit_changed_at_idx on public.order_status_audit(changed_at desc);

create or replace function public.is_admin_or_staff()
returns boolean
language sql
stable
security definer
set search_path = 'public'
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role in ('admin', 'staff')
  );
$$;

drop policy if exists "Admins can view order status audit" on public.order_status_audit;
create policy "Admins can view order status audit"
on public.order_status_audit for select to authenticated
using (public.is_admin_or_staff());

grant select on public.order_status_audit to authenticated;
grant all on public.order_status_audit to service_role;

create or replace function public.log_order_status_change()
returns trigger
language plpgsql
security definer
set search_path = 'public'
as $$
begin
  if old.status is distinct from new.status then
    insert into public.order_status_audit (
      order_id,
      reference,
      previous_status,
      new_status,
      changed_by
    )
    values (
      new.id,
      new.reference,
      old.status,
      new.status,
      auth.uid()
    );
  end if;

  return new;
end;
$$;

drop trigger if exists on_order_status_change on public.orders;
create trigger on_order_status_change
after update of status on public.orders
for each row execute function public.log_order_status_change();

create or replace function public.rls_auto_enable()
returns event_trigger
language plpgsql
security definer
set search_path = 'pg_catalog'
as $$
declare
  cmd record;
begin
  for cmd in
    select *
    from pg_event_trigger_ddl_commands()
    where command_tag in ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      and object_type in ('table', 'partitioned table')
  loop
    if cmd.schema_name is not null
      and cmd.schema_name = 'public'
      and cmd.schema_name not like 'pg_toast%'
      and cmd.schema_name not like 'pg_temp%'
    then
      begin
        execute format(
          'alter table if exists %s enable row level security',
          cmd.object_identity
        );
        raise log 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      exception
        when others then
          raise log 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      end;
    else
      raise log 'rls_auto_enable: skipped % in schema %', cmd.object_identity, cmd.schema_name;
    end if;
  end loop;
end;
$$;

drop event trigger if exists ensure_rls;
create event trigger ensure_rls
on ddl_command_end
when tag in ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
execute function public.rls_auto_enable();
